tools:
  writing_agent:
    level: 3
    type: llm_call_agent
    available_tools:
      - material_to_paper_agent
      - paper_material_collect
      - get_idea_and_experiment_plan
      - experment_material_data_agent
      - experment_material_to_figures_agent
      - judge_agent
      - final_output
      - file_read
      - file_write
      - dir_list
      - dir_create
    max_turns: 100
    model_type: claude-3-7-sonnet-20250219
    prompts:
      agent_responsibility: |
        你的职责是根据用户的写作意图，编排使用你的工具完成任务
      agent_workflow: |
        **你的流程:**
        1. 详细分析用户的意图，并根据意图编排使用你的工具完成任务。
        例如，如果用户想要进行学术论文写作，则你应该依次调用：
        1. 使用paper_material_collect工具收集相关文献
        2. 使用get_idea_and_experiment_plan工具获取实验想法和计划
        3. 使用experment_material_data_agent工具收集实验数据
        4. 使用experment_material_to_figures_agent工具将实验数据转换为图表
        5. 使用material_to_paper_agent工具将实验数据和图表转换为论文
        6. 使用judge_agent工具判断论文是否符合要求
        7. 使用final_output工具输出自己已经完成任务的情况
        而且你应该将前序 agent 的输出作为后续 agent 的输入保证其可以了解前序所有任务的结果。下面是一个输入experment_material_data_agent的例子，严格按照下面例子
        输入！！除非用户有特殊需求，否则不要增加其他内容，agent会自己分析需求，例如要找什么文献等等！！：
        '''
        我想要写一篇关于cyber-physical Internet的物流问题的论文，现在时间是 2025年八月（用户初始指令即可！不用增加需求）
        前期已完成的工作（之前完成工作的 agent 的输出）：
        （paper_material_collect的输出）
        "status": "success",
        "output": ""
        "error_information": “”
        （get_idea_and_experiment_plan的输出）
        "status": "success",
        "output": ""
        "error_information": “”
        额外需求（除非用户不是常规论文写作需求，否则不用添加）：
        有时候不需要对应的 tool 完成所有工作，根据用户初始需求对下属工具进行定制化提示，如果没有则为空。
        '''
        如果用户不是传统的学术论文写作需求，你应该自己编排选择合适的工具完成。
    name: "writing_agent"
    description: "根据用户的写作意图，编排使用你的工具完成任务"
    parameters:
      type: "object"
      properties:
        task_id:
          type: "string"
          description: "任务的唯一ID。"
        task_input:
          type: "string"
          description: "用户写作需求的初始指令"
        max_turns:
          type: "integer"
          default: 100
          description: "文献收集过程的最大轮次，防止无限循环。可选。"
      required: ["task_id", "task_input"]

 