temperature: 0
max_tokens: 0
max_context_window: 100000
base_url: https://openrouter.ai/api/v1
api_key: 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
models:
- openai/openai/gpt-oss-20b
figure_models:
- google/gemini-3-pro-image-preview
compressor_models:
- openai/openai/gpt-oss-20b
read_figure_models:
- openai/google/gemini-3-flash-preview

